---
- name: Add repo key
  apt_key: 
    keyserver: "keys.gnupg.net"
    id: 1C4CBDCDCD2EFD2A
  when: ansible_os_family == "Debian"

- name: add repository
  apt_repository: 
    repo: "{{ item }}"
  with_items:
    - "deb http://repo.percona.com/apt {{ ansible_distribution_release }} main"
    - "deb-src http://repo.percona.com/apt {{ ansible_distribution_release }} main"
  when: ansible_os_family == "Debian"